# DO NOT modify this file by hand, changes will be overwritten
import sys
from dataclasses import dataclass
from inspect import getmembers, isclass
from typing import (
    AbstractSet,
    Any,
    Generic,
    Mapping,
    MutableMapping,
    Optional,
    Sequence,
    Type,
    TypeVar,
)

from cloudformation_cli_python_lib.interface import (
    BaseModel,
    BaseResourceHandlerRequest,
)
from cloudformation_cli_python_lib.recast import recast_object
from cloudformation_cli_python_lib.utils import deserialize_list

T = TypeVar("T")


def set_or_none(value: Optional[Sequence[T]]) -> Optional[AbstractSet[T]]:
    if value:
        return set(value)
    return None


@dataclass
class ResourceHandlerRequest(BaseResourceHandlerRequest):
    # pylint: disable=invalid-name
    desiredResourceState: Optional["ResourceModel"]
    previousResourceState: Optional["ResourceModel"]


@dataclass
class ResourceModel(BaseModel):
    tfcfnid: Optional[str]
    AutoGenerated: Optional[bool]
    Comments: Optional[str]
    Enabled: Optional[bool]
    Id: Optional[str]
    IgnoreErrors: Optional[bool]
    IgnoreWarnings: Optional[bool]
    InstallOn: Optional[Sequence[str]]
    Method: Optional[str]
    Name: Optional[str]
    OriginalDestination: Optional[str]
    OriginalService: Optional[str]
    OriginalSource: Optional[str]
    Package: Optional[str]
    Position: Optional[Sequence["_PositionDefinition"]]
    TranslatedDestination: Optional[str]
    TranslatedService: Optional[str]
    TranslatedSource: Optional[str]

    @classmethod
    def _deserialize(
        cls: Type["_ResourceModel"],
        json_data: Optional[Mapping[str, Any]],
    ) -> Optional["_ResourceModel"]:
        if not json_data:
            return None
        dataclasses = {n: o for n, o in getmembers(sys.modules[__name__]) if isclass(o)}
        recast_object(cls, json_data, dataclasses)
        return cls(
            tfcfnid=json_data.get("tfcfnid"),
            AutoGenerated=json_data.get("AutoGenerated"),
            Comments=json_data.get("Comments"),
            Enabled=json_data.get("Enabled"),
            Id=json_data.get("Id"),
            IgnoreErrors=json_data.get("IgnoreErrors"),
            IgnoreWarnings=json_data.get("IgnoreWarnings"),
            InstallOn=json_data.get("InstallOn"),
            Method=json_data.get("Method"),
            Name=json_data.get("Name"),
            OriginalDestination=json_data.get("OriginalDestination"),
            OriginalService=json_data.get("OriginalService"),
            OriginalSource=json_data.get("OriginalSource"),
            Package=json_data.get("Package"),
            Position=deserialize_list(json_data.get("Position"), PositionDefinition),
            TranslatedDestination=json_data.get("TranslatedDestination"),
            TranslatedService=json_data.get("TranslatedService"),
            TranslatedSource=json_data.get("TranslatedSource"),
        )


# work around possible type aliasing issues when variable has same name as a model
_ResourceModel = ResourceModel


@dataclass
class PositionDefinition(BaseModel):
    MapKey: Optional[str]
    MapValue: Optional[str]

    @classmethod
    def _deserialize(
        cls: Type["_PositionDefinition"],
        json_data: Optional[Mapping[str, Any]],
    ) -> Optional["_PositionDefinition"]:
        if not json_data:
            return None
        return cls(
            MapKey=json_data.get("MapKey"),
            MapValue=json_data.get("MapValue"),
        )


# work around possible type aliasing issues when variable has same name as a model
_PositionDefinition = PositionDefinition


