AWSTemplateFormatVersion: "2010-09-09"

Description: "Example that deploys a AWS instance"

Resources:

    myInstance:
        Type: "Terraform::AWS::Instance"
        Properties:
            Ami: "ami-02fd0b06f06d93dfc"
            InstanceType: "t2.micro"
            NetworkInterface:
              - NetworkInterfaceId: eni-0b1659118c64f9395
                DeviceIndex: 0
              - NetworkInterfaceId: eni-0782460934933f801
                DeviceIndex: 1
